name: Auto deploy with github actions
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: main

jobs:
  install:
    runs-on: ubuntu-latest

 steps:
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 8.6.7
      - name: Checkout action v3
        uses: actions/checkout@v3
